name: Security Scan Pipeline

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

permissions:
  contents: read
  security-events: write

jobs:
  trivy-scan:
    name: Trivy Scanner for Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull Docker Image
        run: |
          docker pull 342934375778.dkr.ecr.ap-northeast-2.amazonaws.com/namespace/security-platform:latest

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "342934375778.dkr.ecr.ap-northeast-2.amazonaws.com/namespace/security-platform:latest"
          format: "table"
          exit-code: "0"
          severity: "CRITICAL,HIGH"


  kyverno-validation:
    name: Validate Kyverno Policies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Kyverno CLI
        uses: kyverno/action-install-cli@v0.2.0

      - name: Verify Installation
        run: kyverno version

      - name: Validate Good Resource
        continue-on-error: true
        run: |
          kyverno apply kubernetes/policies/*.yaml \
          --resource kubernetes/resources/good-deployment.yaml

      - name: Validate Bad Resource
        continue-on-error: true
        run: |
          kyverno apply kubernetes/policies/*.yaml \
          --resource kubernetes/resources/bad-deployment.yaml

      - name: Generate SARIF Report
        uses: aquasecurity/trivy-action@master 
        with: 
          image-ref: "342934375778.dkr.ecr.ap-northeast-2.amazonaws.com/namespace/security-platform:latest" 
          format: "sarif" 
          output: "trivy-results.sarif" 
          exit-code: "0"

      - name: Upload SARIF Report 
        uses: github/codeql-action/upload-sarif@v4 
        with: 
          sarif_file: trivy-results.sarif
